"""Pydantic models defining the data architecture for the factory pipeline."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field, field_validator


class DocumentType(str, Enum):
    PDF = "pdf"
    TEXT = "text"
    MARKDOWN = "markdown"
    HTML = "html"
    CSV = "csv"
    JSON = "json"
    URL = "url"
    UNKNOWN = "unknown"


class TaskType(str, Enum):
    QA = "qa"
    SUMMARIZATION = "summarization"
    CLASSIFICATION = "classification"
    EXTRACTION = "extraction"
    CUSTOM = "custom"


class QualityMetric(str, Enum):
    TOXICITY = "toxicity"
    BIAS = "bias"
    DIVERSITY = "diversity"
    COHERENCE = "coherence"
    OVERALL = "overall"


class Document(BaseModel):
    """Represents a raw ingested document from any source."""

    id: str = Field(default_factory=lambda: f"doc_{uuid4().hex[:12]}")
    source: str
    source_type: DocumentType
    content: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    loaded_at: datetime = Field(default_factory=datetime.utcnow)
    word_count: Optional[int] = None

    @field_validator("content")
    @classmethod
    def content_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Document content cannot be empty")
        return v

    def compute_word_count(self) -> int:
        self.word_count = len(self.content.split())
        return self.word_count


class TextChunk(BaseModel):
    """A segmented piece of a document after processing."""

    id: str = Field(default_factory=lambda: f"chunk_{uuid4().hex[:12]}")
    document_id: str
    index: int
    text: str
    token_estimate: int = 0
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("text")
    @classmethod
    def text_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Chunk text cannot be empty")
        return v

    def compute_token_estimate(self) -> int:
        self.token_estimate = len(self.text.split())
        return self.token_estimate


class TaskTemplate(BaseModel):
    """A recipe card defining how to generate training examples."""

    id: str = Field(default_factory=lambda: f"tmpl_{uuid4().hex[:8]}")
    name: str
    task_type: TaskType
    description: str
    system_prompt: str
    user_prompt_template: str
    instructions: str = ""
    constraints: Dict[str, Any] = Field(default_factory=dict)
    version: str = "1.0.0"
    created_at: datetime = Field(default_factory=datetime.utcnow)


class TaskExample(BaseModel):
    """A single training example generated by the factory."""

    id: str = Field(default_factory=lambda: f"ex_{uuid4().hex[:12]}")
    task_type: TaskType
    task_name: str
    input: str
    expected_output: str
    source_chunk_id: Optional[str] = None
    source_document_id: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    quality_scores: Optional[Dict[str, float]] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "task_type": self.task_type.value,
            "task_name": self.task_name,
            "input": self.input,
            "expected_output": self.expected_output,
            "source_chunk_id": self.source_chunk_id,
            "metadata": self.metadata,
            "quality_scores": self.quality_scores,
        }


class QualityReport(BaseModel):
    """Evaluation report for a training example or dataset batch."""

    id: str = Field(default_factory=lambda: f"qr_{uuid4().hex[:8]}")
    example_id: str
    scores: Dict[str, float] = Field(default_factory=dict)
    issues: List[str] = Field(default_factory=list)
    passed: bool = True
    evaluated_at: datetime = Field(default_factory=datetime.utcnow)

    def add_score(self, metric: QualityMetric, value: float) -> None:
        key = metric.value if isinstance(metric, QualityMetric) else metric
        self.scores[key] = value

    def add_issue(self, issue: str) -> None:
        self.issues.append(issue)
        self.passed = False

    @property
    def overall_score(self) -> float:
        if not self.scores:
            return 0.0
        return sum(self.scores.values()) / len(self.scores)


class Dataset(BaseModel):
    """A collection of training examples ready for export."""

    id: str = Field(default_factory=lambda: f"ds_{uuid4().hex[:8]}")
    name: str = "untitled_dataset"
    examples: List[TaskExample] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    quality_reports: List[QualityReport] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    def add_example(self, example: TaskExample) -> None:
        self.examples.append(example)

    def add_report(self, report: QualityReport) -> None:
        self.quality_reports.append(report)

    @property
    def size(self) -> int:
        return len(self.examples)

    @property
    def passed_quality(self) -> List[TaskExample]:
        passed_ids = {r.example_id for r in self.quality_reports if r.passed}
        return [ex for ex in self.examples if ex.id in passed_ids]

    def export(self, path: str, format: str = "jsonl") -> str:
        import json

        examples = [ex.to_dict() for ex in self.examples]
        full = {
            "dataset_id": self.id,
            "name": self.name,
            "size": self.size,
            "metadata": self.metadata,
            "examples": examples,
        }

        if format == "jsonl":
            with open(path, "w", encoding="utf-8") as f:
                for ex in examples:
                    f.write(json.dumps(ex, ensure_ascii=False) + "\n")
            return path

        with open(path, "w", encoding="utf-8") as f:
            json.dump(full, f, indent=2, ensure_ascii=False)
        return path
